# Generated by Django 5.1.6 on 2025-03-06 07:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('type', models.CharField(choices=[('Sedan', 'Седан'), ('SUV', 'Внедорожник'), ('Hatchback', 'Хэтчбек'), ('Cabriolet', 'Кабриолет'), ('Coupe', 'Купе'), ('Minivan', 'Минивэн'), ('Pickup', 'Пикап')], default='Sedan', max_length=20, verbose_name='Тип')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час (тг)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='CarLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rental.car', verbose_name='Автомобиль')),
            ],
        ),
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rental.car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel', verbose_name='Пользватель')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.dealer', verbose_name='Дилер'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало аренды')),
                ('end_time', models.DateTimeField(verbose_name='Окончание аренды')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма штрафа')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel', verbose_name='Пользователь')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.rental', verbose_name='Аренда')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TOP_UP', 'Пополнение баланса'), ('RENTAL', 'Оплата аренды')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TripTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время фиксации')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='rental.rental', verbose_name='Аренда')),
            ],
        ),
    ]
