# Generated by Django 5.1.6 on 2025-03-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PB95', 'PB95'), ('PB98', 'PB98')], default='PB95', max_length=20, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Механика'), ('Automatic', 'Автоматическая')], default='Manual', max_length=20, verbose_name='Трансмиссия'),
        ),
    ]
